services:
  app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Mapeia uma pasta local para salvar o banco de dados
    networks:
      - monitoramento
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: ["tunnel", "--no-autoupdate", "run", "--token", "${CLOUDFLARED_TUNNEL_TOKEN}", "--url", "http://app:8501"]
    depends_on:
      - app
    networks:
      - monitoramento
    restart: unless-stopped

networks:
  monitoramento:
    driver: bridge